### ISSUE TITLE
Crash app on startup

### ISSUE THREAD

**Issue by zakblacki** [laitooo/Warewolf-Online#1]
app crash after splash screen on UserData and MainActivity

here is logcat any fix ? 

     `java.lang.RuntimeException: Unable to start activity ComponentInfo{zxc.laitooo.warewolfonline/zxc.laitooo.warewolfonline.activities.MainActivity}: java.lang.NumberFormatException: s == null
     Caused by: java.lang.NumberFormatException: s == null
        at zxc.laitooo.warewolfonline.user.UserData.getUser(UserData.java:35)
        at zxc.laitooo.warewolfonline.activities.MainActivity.onCreate(MainActivity.java:117)
`

Also I noticed there a few roles missing hunter, protector etc....I hope you consider adding them

**Comment by laitooo** [comment]
did u start the node.js server + created the database ?
it's probably because the user hasn't been created successfully .

Sorry but I decided to continue developing this game in other private repo and kept this public if anyone needs it .

**Comment by zakblacki** [comment]
Thank you for replying, 
I did start the server testing.js and main.js and changed the ip inside Links.java and app/index/main
and I created mydb in wamp  as below

but I couldn't start app.js and index.js because of this  `io = require('socket.io').listen(server);`  
I did node install socket.io but same issue not sure if it's required or If I'm missing something ?
Or does the ip need to match the phone ip ? 
![image](https://user-images.githubusercontent.com/29728429/98438252-48749200-20e9-11eb-8b81-76b069e5dd0a.png)

Also I hope you'll keep working on this the bugs at least  I really like the interface, seems promising

**Comment by laitooo** [comment]
the main.js and index.js are useless , u can delete them
start the app.js 
install all required models 
the app really depends 90% on socket.io , so make sure you install it
if u are using localhost u should insert you phone Ip address 
I'm planning to publish alpha version on google play soon :)

**Comment by zakblacki** [comment]
![image](https://user-images.githubusercontent.com/29728429/98453013-e782a380-2154-11eb-981a-36f0079024c8.png)
about this point where do I import this database

**Comment by laitooo** [comment]
Since you are using phpMyAdmin you see many choices at the top of the page including Export and Import
Choose import and choose the mydb.sql file and click go
the database will be imported .
so you don't have to create it all.

**Comment by zakblacki** [comment]
Edit : 
I had to update app.js to make it work 
`io = require('socket.io').listen(server);`
to 
`io = require('socket.io')(server);`
But the app still crash on emulator after splashscreen  same logcat as mentioned up previously

**Comment by laitooo** [comment]
Just updated SplashScreenActivity.java
try it out

**Comment by zakblacki** [comment]
Thank you, just quick note 
you should provide the correct context of your class instead of `(this, LoginActivity.class)`

Now I manage to see the authentication page but whenever I try to login or signup I'm getting two different error on the server
apparently it came from imagesManager.js and myNetwork.js

Edit : 
for signup I created manually the folder public\icons and added the assets icon8.png but same issue 
it giving me "Network connection Error" 

     `C:\Users\zakbl\OneDrive\Desktop\Werewolf-Online-master\nodejs\imagesManager.js:16
                if (err) throw err;
                         ^
     [Error: ENOENT: no such file or directory, open 'C:\Users\zakbl\OneDrive\Desktop\Werewolf-Online- 
     master\nodejs\public\images\image3.png'] {
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Users\\zakbl\\OneDrive\\Desktop\\Werewolf-Online-master\\nodejs\\public\\images\\image3.png'
     }
`

- Sign In button 

     `C:\Users\AppData\Roaming\npm\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^
TypeError: callback is not a function
    at Query.<anonymous> (C:\Users\Desktop\Werewolf-Online-master\nodejs\myNetwork.js:20:13)
    at Query.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zakbl\AppData\Roaming\npm\node_modules\mysql\lib\protocol\Protocol.js:38:16)`

**Comment by laitooo** [comment]
sorry for too much errors 
for the signup problem I update the 'imagesManager.js' and update the readme check it out
if you have already some users I advice you to clear the users database and uninstall the app and try again.
for the login problem I update 'app.js' .
I hope that helps .

**Comment by zakblacki** [comment]
So the good news I did manage to login and sign up, 
but when it comes to 
Create group, or game option or adding friend they cause "Network connection error" 

![image](https://user-images.githubusercontent.com/29728429/98951622-c7f3ce00-24fa-11eb-9ee9-d8f84cd5586e.png)

Also the database you sent is set to read only so we cannot delete record from it 
![image](https://user-images.githubusercontent.com/29728429/98951750-eeb20480-24fa-11eb-92e0-571217b9ab7d.png)

to be honest I was hoping the app would be similar to this one
[Warewolf app](https://play.google.com/store/apps/details?id=com.victorjouin.loup)
The only downside from it is that we have to pay in order to have all the classical role available and we cannot edit the number of wolf and there is no voice feature 

So I hope, you consider adding them

**Comment by laitooo** [comment]
can you provide the node.js error log?
for the database It's not read only
you can empty any table by just clicking on the database name , it will show the tables and it's options like insert , empty and drop
just choose empty.

for my app I added main characters and secondary characters and I'm planning on adding more soon and they are like 15 for now and I'm planning to keep all of them free.
also I didn't add the number of wolfs and villagers yet but it's on my todo list.
In my last version I'm working on I added the voice chat .
it has some problems but it partially work :) 

I'm planning on keeping the source code private but I let this public so people don't have to start from zero.

**Comment by zakblacki** [comment]
Sorry for late response I'm kinda new on nodejs usage so I'm not sure where I can find the error log

**Comment by laitooo** [comment]
in the console you start the app.js from 
everything happens it gets written there .

**Comment by zakblacki** [comment]
Hi, so thing is there isn't any error in the console app.js 

when are you planning on releasing alpha version play store ?

**Comment by laitooo** [comment]
hey , sorry I was a busy with exams 
to help you fix the issue text me on telegram : https://t.me/Laito_san
probably alpha version will be out two weeks from now.
